### ISSUE TITLE
滑动时图片会跳变

### ISSUE THREAD

**Issue by smallmuou** [openboy2012/DDCollectionViewFlowLayout#2]
![issue](https://cloud.githubusercontent.com/assets/2653709/9033723/7c8a1508-39fc-11e5-8042-4c7972530de2.gif)

**Comment by openboy2012** [comment]
请检查你的图片Size大小是不是固定的

**Comment by smallmuou** [comment]
大小确实不是固定的，不过后来我找到了另一个开源库chiahsien/CHTCollectionViewWaterfallLayout

**Comment by openboy2012** [comment]
大小不固定肯定会变化的
