### ISSUE TITLE
layout 的 minimumInteritemSpacing 之类的属性不生效

### ISSUE THREAD

**Issue by Whirlwind** [openboy2012/DDCollectionViewFlowLayout#3]
Layout 可以设置默认属性，例如 minimumLineSpacing ，minimumInteritemSpacing，sectionInset 这些可以不通过 delegate 来设置。目前貌似无效。

**Comment by openboy2012** [comment]
你是指获取storyboard或者xib中的默认值么？

**Comment by Whirlwind** [comment]
也算是吧，代码也可以啊。有这些属性，不需要调用Delegate

**Comment by openboy2012** [comment]
已经修复，请更新代码

**Comment by Whirlwind** [comment]
更新一下 spec 版本号呗。另外项目根目录也放一份spec 描述文件吧，用于源码引用。

**Comment by Whirlwind** [comment]
sectionInset 依然无效！！看了代码，第135行，初始值也应该取 self. sectionInset 而不是 Zero
