### ISSUE TITLE
collectionView 未设置 numberOfSections 会导致 crash

### ISSUE THREAD

**Issue by Whirlwind** [openboy2012/DDCollectionViewFlowLayout#4]
collectionView 采用datasource 设置 section 数量，那么 self.collectionView.numberOfSections 总是 0，导致后面数组越界引起crash

**Comment by openboy2012** [comment]
numberOfSections方法是dataSource的必选方法，你不设置是不合理的

**Comment by Whirlwind** [comment]
我设置了datasource的numberOfSections 的回调，并没有直接设置 collectionView.numberOfSections. 做了如下修改即可正常：

```
    NSUInteger numberOfSections = self.collectionView.numberOfSections;
    if ([self.collectionView.dataSource respondsToSelector:@selector(numberOfSectionsInCollectionView:)]) {
        numberOfSections = [self.collectionView.dataSource numberOfSectionsInCollectionView:self.collectionView];
    }
```

**Comment by Whirlwind** [comment]
再者，`- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView;` 该 datasource 为可选方法，不是必选的。

如果没有设置 collectionView.numberOfSections，也没设置 dataSource 回调，系统默认是 1。但是直接取 collectionView.numberOfSections 返回的是0.
