### ISSUE TITLE
header 或者 footer 为nil会导致crash

### ISSUE THREAD

**Issue by Whirlwind** [openboy2012/DDCollectionViewFlowLayout#6]
在使用系统的 FlowLayout 的时候，有实现 header 和 footer 的相关回调：
```
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout referenceSizeForFooterInSection:(NSInteger)section {
    if (section == 0) {
        return CGSizeZero;
    } else { return CGSizeMake(320, 10); }
}
```

系统判断，如果高度为0，不会调用 `- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath`.

目前的 DDCollectionViewLayout 在 `- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect` 中，没有判断 height 为 0 的情况：
```
        // Check footer layout attributes's rectangles if intersectes the collectionView's rectangles.
        if ([self.headerFooterItemAttributes[UICollectionElementKindSectionFooter] count] > sectionIdx) {
            UICollectionViewLayoutAttributes *footerAttribute = self.headerFooterItemAttributes[UICollectionElementKindSectionFooter][sectionIdx];
            BOOL isVisible = CGRectIntersectsRect(rect, footerAttribute.frame);
            if (isVisible && footerAttribute)
                [itemAttrs addObject:footerAttribute];
            self.currentEdgeInsets = UIEdgeInsetsZero;
        } else {
            self.currentEdgeInsets = [self.sectionInsetses[sectionIdx] UIEdgeInsetsValue];
        }
```
应该修改为 
```
            if (isVisible && footerAttribute && footerAttribute.frame.size.height > 0)
```

header 同理。

**Comment by openboy2012** [comment]
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath 方法不是nullable的，必须要返回非nil的reuseableView对象才行。
DDCollectionViewFlowLayout本身就是继承了UICollectionViewFlowLayout，DDCollectionViewDelegateFlowLayout也是继承了DDCollectionViewDelegateFlowLayout，本质上DDCollectionViewFlowLayout只是UICollectionViewFlow的扩展，所有的使用习惯都是参考UICollectionViewFlowLayout。
当然，加个判断增加代码的健壮性也是不错的。

**Comment by Whirlwind** [comment]
```
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath
```
 方法确实不是nullable的，因为确实不能返回nil！
但是，再FlowLayout布局中，如果不想要header 或者 footer，不是在这个函数返回 nil，而是 size 那里返回 0.
```
- (CGSize)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout *)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section;
--
Asks the delegate for the size of the header view in the specified section.If you do not implement this method, the flow layout uses the value in its headerReferenceSize property to set the size of the header.During layout, only the size that corresponds to the appropriate scrolling direction is used. For example, for the vertical scrolling direction, the layout object uses the height value returned by your method. (In that instance, the width of the header would be set to the width of the collection view.) If the size in the appropriate scrolling dimension is 0, no header is added.
collectionViewThe collection view object displaying the flow layout.collectionViewLayoutThe layout object requesting the information.sectionThe index of the section whose header size is being requested. 

If you return a value of size (0, 0), no header is added.
```
注意最后一句

**Comment by openboy2012** [comment]
我的意思是你如果不实现- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath 这个方法就可以了。

**Comment by Whirlwind** [comment]
需求必须得实现啊。

当section == 0 时，无footer和header，其余情况有footer。

这种情况就得通过 referenceSizeForFooterInSection 这种回调返回 CGSizeZero 来不显示 footer

**Comment by openboy2012** [comment]
那你只要保证- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath 返回非nil的UI对象就可以了。

**Comment by Whirlwind** [comment]
官方文档说，不需要header和footer的时候，返回size为0即可。

再者说，我也觉得没必要构造一个size 为0的view吧？无论从性能还是设计方式上，都是无意义的

**Comment by openboy2012** [comment]
一开始我就阐述了DDCollectionViewFlowLayout只是UICollectionViewFlowLayout的扩展，使用方式参考UICollectionViewFlowLayout，你所表达的性能和设计都是苹果工程师设计的。
